sudo: required
language: node_js
services:
- docker
node_js:
- 11.12
before_install:
- openssl aes-256-cbc -K $encrypted_213c7ad97f24_key -iv $encrypted_213c7ad97f24_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- export DOCKER_ID_USER="$docker_user"
install:
- cp env.example.json env.json
- docker build -t lua-china:0.1 .
- docker login -u $docker_user -p $docker_password
- docker tag lua-china:0.1 $DOCKER_ID_USER/lua-china:0.1
- docker push $DOCKER_ID_USER/lua-china:0.1
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "(docker stop lua-china) && (docker rm -f lua-china || true) && (docker rmi -f horan/lua-china:0.1 || true)"
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "docker run -p 10.31.231.178:8888:80 --name=lua-china -d horan/lua-china:0.1"
after_success:
- rm -rf ~/.ssh
