sudo: required
language: node_js
services:
- docker
node_js:
- 11.12
before_install:
- openssl aes-256-cbc -K $encrypted_213c7ad97f24_key -iv $encrypted_213c7ad97f24_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- export DOCKER_ID_USER="$docker_user"
install:
- cp env.example.json env.json
- docker build -t $DOCKER_ID_USER/lua-china:$TRAVIS_COMMIT .
- docker login -u $docker_user -p $docker_password
- docker push $DOCKER_ID_USER/lua-china:$TRAVIS_COMMIT
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "docker pull horan/lua-china:$TRAVIS_COMMIT && (docker rm -f lua-china || true)"
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "docker run -p 10.31.231.178:8888:80 --name=lua-china -d horan/lua-china:$TRAVIS_COMMIT"
after_success:
- rm -rf ~/.ssh
